server:
  port: 8082
spring:
  application:
    name: Single-Data-Source-Mysql
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: app_user
    password: app_user
    url: jdbc:mysql://localhost:3306/persontest?useSSL=false&characterEncoding=utf8
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
